<?php
/**
 * Actions Framework.
 *
 * WARNING: This file is part of the core Actions Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Actions 
 * @author  WPDevHQ
 * @license GPL-2.0+
 * @link    http://www.wpdevhq.com/themes/actions/
 */

//* Initialize Actions

actions_search();